name: start workflow deployments
on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    name: Detect changed files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: find yaml files
        id: changed-yml-files
        uses: tj-actions/changed-files@v35
        with:
          files: models/*/*/**/*.{yml, yaml}
          json: "true"
          json_raw_format: "true"
      - name: Detect data products to deploy
        id: changed-yml-files-setter
        if: steps.changed-yml-files.outputs.any_changed == 'true'
        run: |
          echo "One or more deployments files has changed."
          echo "All modified files are: ${{ steps.changed-yml-files.outputs.all_modified_files }}"
          JOBS_TO_DEPLOY=$(echo '${{ steps.changed-yml-files.outputs.all_modified_files }}' | jq -c '. | map(select(startswith("models")) | split("/") | .[2]) | unique')
          echo "Detected changed data products are: $JOBS_TO_DEPLOY"
          echo "matrix=$JOBS_TO_DEPLOY" >> "$GITHUB_OUTPUT"
          echo files_found
    outputs:
      matrix: ${{ steps.changed-yml-files-setter.outputs.matrix }}

  deploy:
    needs: detect-changes
    if: ${{ contains(needs.detect-changes.result.files_found, 'files_founds') }}
    strategy:
      fail-fast: false
      matrix:
        list-of-args: ${{ fromJSON(needs.detect-changes.outputs.matrix) }}
    uses: ./.github/workflows/deploy-qa-jobs.yml
    with:
      arg: ${{ matrix.list-of-args }}